[project]
name = "photo-index"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorgram-py>=1.2.0",
    "nltk>=3.9.2",
    "ollama>=0.6.1",
    "pillow>=12.0.0",
    "sqlalchemy>=2.0.45",
]
